// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Validate environment variables
if (!SUPABASE_URL || SUPABASE_URL === 'https://placeholder.supabase.co') {
  console.error('❌ VITE_SUPABASE_URL is not set or is using placeholder value!');
}

if (!SUPABASE_PUBLISHABLE_KEY || SUPABASE_PUBLISHABLE_KEY === 'YOUR_SUPABASE_ANON_KEY_HERE' || SUPABASE_PUBLISHABLE_KEY === 'placeholder-key') {
  console.error('❌ VITE_SUPABASE_PUBLISHABLE_KEY is not set or is using placeholder value!');
  console.error('👉 Get your anon key from: https://supabase.com/dashboard/project/rvpkcwskkovqhfwwrdeq/settings/api');
}

const url = SUPABASE_URL || 'https://rvpkcwskkovqhfwwrdeq.supabase.co';
const key = SUPABASE_PUBLISHABLE_KEY || 'placeholder-key';

export const supabase = createClient<Database>(url, key, {
  auth: {
    storage: typeof window !== 'undefined' ? localStorage : undefined as any,
    persistSession: true,
    autoRefreshToken: true,
  }
});